services:
  ghost:
    image: ghost:6-alpine
    container_name: anotes-ctnr
    restart: always
    ports:
      - 2368:2368
    depends_on:
      - dbsvr
    environment:
      database__client: mysql
      database__connection__host: dbsvr
      database__connection__user: zenusr
      database__connection__password: strongPass!2024
      database__connection__database: anotedb
      url: http://localhost:2368
      # NODE_ENV=production
    volumes:
      - ./content:/var/lib/ghost/content

  dbsvr:
    image: mariadb:11.4
    container_name: anotes-db-ctnr
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: superStrong!2024
      MYSQL_USER: zenusr
      MYSQL_PASSWORD: strongPass!2024
      MYSQL_DATABASE: anotedb
    volumes:
      - ./db:/var/lib/mysql
      - ./env/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  content:
  db:
