services:
  ghost:
    image: ghost:6-alpine
    container_name: anotes-ctnr
    restart: always
    ports:
      - 2368:2368
    environment:
      - database__client: sqlite3
      - database__connection__filename: /var/lib/ghost/content/data/anotes-dev.db
      - url: http://localhost:2368
    volumes:
      - ./content:/var/lib/ghost/content
      - ./db-dev:/var/lib/ghost/content/data/

volumes:
  content:
  db-dev:
